apiVersion: v2
actions:
  - name: "Deploy using helm"
    events:
      - name: "sh.keptn.event.deployment.triggered"
    tasks:
      - name: "Run helm"
        files:
          - /helm-charts
        env:
          - name: IMAGE
            value: "$.data.configurationChange.values.image"
            valueFrom: event
        image: "alpine/helm:3.7.2"
        serviceAccount: "jes-deploy-using-helm"
        cmd: ["helm"]
        args: ["upgrade", "--create-namespace", "--install", "-n", "mysample", "helloservice", "/keptn/helm-charts", "--set", "image=$(IMAGE)", "--wait"]
  
  - name: "Promote phased argo rollouts"
    events:
      - name: "sh.keptn.event.release.triggered"
    tasks:
      - name: "Run argo rollouts in phased manner"
        image: "bitnami/kubectl"
        serviceAccount: "jes-deploy-using-helm"
        cmd: ["sh"]
        # args: ["-c", "curl -LO https://github.com/argoproj/argo-rollouts/releases/latest/download/kubectl-argo-rollouts-linux-amd64; chmod +x ./kubectl-argo-rollouts-linux-amd64; sudo mv ./kubectl-argo-rollouts-linux-amd64 /usr/local/bin/kubectl-argo-rollouts; kubectl argo rollouts promote helloservice -n mysample"]
        args: ["-c", "sleep 3000"]