apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: helloservice
  namespace: {{ .Release.Namespace }} 
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: helloservice
  template:
    metadata:
      labels:
        app: helloservice
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: server
        image: {{ .Values.image}}
        imagePullPolicy: Always
        ports:
        - containerPort: 9000
        env:
        - name: PORT
          value: "9000"
  strategy:
    canary: #Indicates that the rollout should use the Canary strategy
      steps:
      - setWeight: 10
      - pause:
          duration: 10s # 1 hour
      - setWeight: 70
      - pause: {} # pause indefinitely
